# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

burkardt_polynomial_dif <- function(c1, Powers, dif) {
    .Call(`_mpolynomial_burkardt_polynomial_dif`, c1, Powers, dif)
}

burkardt_polynomial_value <- function(c, Powers, x) {
    .Call(`_mpolynomial_burkardt_polynomial_value`, c, Powers, x)
}

