# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

burkardt_polynomial_dif <- function(c1, Powers, dif) {
    .Call(`_mpolynomial_burkardt_polynomial_dif`, c1, Powers, dif)
}

burkardt_polynomial_value <- function(c, Powers, x) {
    .Call(`_mpolynomial_burkardt_polynomial_value`, c, Powers, x)
}

rcpp_differentiate <- function(Coeffs, Degrees, DWR) {
    .Call(`_mpolynomial_rcpp_differentiate`, Coeffs, Degrees, DWR)
}

rcpp_evaluate <- function(Coeffs, Degrees, Values) {
    .Call(`_mpolynomial_rcpp_evaluate`, Coeffs, Degrees, Values)
}

rcpp_rank_grlex <- function(Powers) {
    .Call(`_mpolynomial_rcpp_rank_grlex`, Powers)
}

rcpp_unrank_grlex <- function(m, rank) {
    .Call(`_mpolynomial_rcpp_unrank_grlex`, m, rank)
}

